drop table if exists users, items, bookings, requests, comments;

create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique
);

create table if not exists items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(2000) not null,
    available boolean not null,
    owner_id integer references users(id) on delete cascade,
    request_id int
);

create table if not exists bookings (
    id bigint generated by default as identity primary key,
    item_id int references items(id) on delete cascade,
    start_date timestamp not null,
    end_date timestamp not null,
    user_id int references users(id) on delete cascade,
    status varchar(50) not null
);

create table if not exists requests (
    id bigint generated by default as identity primary key,
    description varchar(2000) not null,
    requestor_id int references users(id) on delete cascade,
    creation_date date not null
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    item_id int references items(id) on delete cascade,
    user_id int references users(id) on delete cascade,
    text varchar(2000) not null,
    created timestamp not null
);
